const express = require('express');
const authRoutes = require('./auth.routes');
const mediaRoutes = require('./media.routes');
const ctaRoutes = require('./cta.routes');
const socialRoutes = require('./social.routes');
const categoryRoutes = require('./category.routes');
const tagRoutes = require('./tag.routes');
const heroRoutes = require('./hero.routes');
const navigationRoutes = require('./navigation.routes');
const aboutRoutes = require('./about.routes');
const projectRoutes = require('./project.routes');
const experienceRoutes = require('./experience.routes');
const educationRoutes = require('./education.routes');
const skillRoutes = require('./skill.routes');
const serviceRoutes = require('./service.routes');
const testimonialRoutes = require('./testimonial.routes');
const contactRoutes = require('./contact.routes');
const settingRoutes = require('./setting.routes');
const eventRoutes = require('./event.routes');
const blogCategoryRoutes = require('./blogCategory.routes');
const blogTagRoutes = require('./blogTag.routes');
const blogRoutes = require('./blog.routes');
const blogCommentRoutes = require('./blogComment.routes');
const analyticsRoutes = require('./analytics.routes');
const achievementRoutes = require('./achievement.routes');
const certificationRoutes = require('./certification.routes');
const cvImportRoutes = require('./cvImport.routes');
const router = express.Router();

router.get('/health', (req, res) => {
  res.json({ success: true, message: 'API is healthy' });
});

router.use('/auth', authRoutes);
router.use('/media', mediaRoutes);
router.use('/ctas', ctaRoutes);
router.use('/social', socialRoutes);
router.use('/categories', categoryRoutes);
router.use('/tags', tagRoutes);
router.use('/hero', heroRoutes);
router.use('/navigation', navigationRoutes);
router.use('/about', aboutRoutes);
router.use('/projects', projectRoutes);
router.use('/experience', experienceRoutes);
router.use('/education', educationRoutes);
router.use('/skills', skillRoutes);
router.use('/services', serviceRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/contact', contactRoutes);
router.use('/settings', settingRoutes);
router.use('/events', eventRoutes);
router.use('/blog-categories', blogCategoryRoutes);
router.use('/blog-tags', blogTagRoutes);
router.use('/blog', blogRoutes);
router.use('/blog-comments', blogCommentRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/achievements', achievementRoutes);
router.use('/certifications', certificationRoutes);
router.use('/cv', cvImportRoutes);

module.exports = router;
